<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-EGH5GRK4" ignored="0" name="充值接口" tests="5" failures="4" timestamp="23 八月 2020 04:14:20 GMT" time="1.915" errors="0">
  <testcase name="test" time="0.094" classname="com.api.cases.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.RechargeCase.test(RechargeCase.java:47)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.124" classname="com.api.cases.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.RechargeCase.test(RechargeCase.java:47)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.106" classname="com.api.cases.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.RechargeCase.test(RechargeCase.java:47)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.106" classname="com.api.cases.RechargeCase">
    <failure type="java.lang.AssertionError" message="expected [passed] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [passed] but found [failed]
at com.api.cases.RechargeCase.test(RechargeCase.java:47)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="1.32" classname="com.api.cases.RechargeCase"/>
</testsuite> <!-- 充值接口 -->
